### PR TITLE
Bypass requestPermission call if permission is already non-default

### PR DESCRIPTION
**Pull request by mshick**
Per issue #84. It seems like the issue is that Fluid apps have a pre-set `Notification.permission` value and will not fire the `Notification.requestPermission` callback. 

The following PR changes the `Push.request` method to first check for an existing, non-default `Notification.permission` value before attempting to request permissions.

Also included is a simple test to ensure `requestPermission` is not called if `Push.get` returns a non-default value.

Karma test are passing with FF, and I've personally tested in latest Chrome, Fluid and Safari. All appear to work correctly.

### CODE REVIEW

**Comment by Nickersoft** [comment]
👍

**Comment by mshick** [comment]
Awesome, thanks for reviewing so quickly. Think you'll be able to push a version bump to npm soon?

**Comment by Nickersoft** [comment]
Definitely.. there has been a long standing bug with notification events using serviceworkers, but I think I'm close to getting it resolved. Didn't want to publish a new version until that was fixed. At least the current version throws an error on mobile. If I published now there wouldn't be any error and no one would know why it's not working :/ Also, after this PR is merged as well as that fix it should be ready to publish :)

**Comment by mshick** [comment]
Totally makes sense. Thanks for the explanation. I'll keep an eye out for the update.

**Comment by mshick** [comment]
@Nickersoft sorry to bother, but any word on progress here? Is a patch release possible?

**Comment by Nickersoft** [comment]
@mshick Just in case you didn't see, v0.0.12 was just released a few days ago: https://github.com/Nickersoft/push.js/releases/tag/v0.0.12

I apologize for the wait.

**Comment by mshick** [comment]
Spotted it. Thanks!

**Pull request merged**
