### PR TITLE
Fix callback is not defined error

### PR DESCRIPTION
**Pull request by jcgertig**
When using `Push.Permission.request` I was getting callback is not defined. Just added a `var` to initialize it.

### CODE REVIEW

**Comment by Nickersoft** [comment]
Hi @jcgertig! Thanks for the PR (sorry it took so long to get around to this)! I noticed you have a Travis CI test failing... could you fix the error and then update the PR? Once all tests pass I'd be happy to merge it in :)

**Comment by beanoagin** [comment]
Hello

**Comment by Nickersoft** [comment]
Hi...?

**Comment by Nickersoft** [comment]
Anyway, I believe I myself caught this issue while working on the v1.0 release, and all of the new tests are passing. This fix will be released soon, so closing this PR.

**Pull request closed without merging**
