### PR TITLE
Add type overload for Push.Permission.request()

### LINKED ISSUE #243: Types overload missing for Push.Permission.request()
`Push.Permission.request()`can either be called with 2 callback functions as parameters, or with no parameter at all, and in that cases, returns a Promise.

`index.d.ts` should be updated to take the two call signatures into account.

I can make a PR to fix that.

Regards,

### PR DESCRIPTION
**Pull request by Jicmou**
Fixes #243

### CODE REVIEW

**Comment by theLufenk** [comment]
@Jicmou Thank you for this.
There seems to be a test failing. Can you look into it please.

@Nickersoft LGTM. Can be merged.

**Review by theLufenk — DISMISSED** [review]

**Comment by Jicmou** [comment]
@theLufenk  Thanks for approving.

I can reproduce the failing CI on `master`. Run the following commands:

```
npm run test
// passing
npm run build
// builds sucessfully
npm run test
// failing
```
I ran the first two commands before commiting, as stated in the `CONTRIBUTING.md`, Travis ran the third.

I could submit my PR without the build though, as `index.d.ts`has no impact on the build.

**Comment by theLufenk** [comment]
@Nickersoft Over to you.

**Review by theLufenk — APPROVED** [review]

**Comment by theLufenk** [comment]
*nudge* @Nickersoft

**Review by Nickersoft — APPROVED** [review]

**Pull request closed without merging**
