### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by hbarcelos**
Please have a look on commit comments, they have all the information you need.

### CODE REVIEW

**Comment by Nickersoft** [comment]
Seems like quite a few tests have failed... could you look into why? Other than that, your changes look good and appropriate.

**Comment by hbarcelos** [comment]
I'll check them when I get home later today.

**Comment by Nickersoft** [comment]
👍

**Comment by hbarcelos** [comment]
I made a mess with git, but it's working now.

**Comment by Nickersoft** [comment]
Would you mind squashing those into a single commit?

**Comment by hbarcelos** [comment]
@Nickersoft if you check [this link](https://help.github.com/articles/about-pull-request-merge-squashing/), there should be a "built-in" squashing funcionality on github itself.

If you cannot see such option, please let me know and I'll get this fixed.

**Comment by Nickersoft** [comment]
@hbarcelos Oh wow... I didn't know that. Guess you learn something new everyday haha. However, I'm still not seeing the "Squash" button, despite having the feature turned on in settings. Mind taking care of it?

**Comment by hbarcelos** [comment]
No problem. Working on it already.

**Comment by hbarcelos** [comment]
I had to delete and recreate my fork. Making another pull request now.

**Pull request closed without merging**
