### PR TITLE
Add `silent` option

### PR DESCRIPTION
**Pull request by sugarshin**
Hi,

Could you review this. I added `silent` option.

### CODE REVIEW

**Comment by Nickersoft** [comment]
Hey! Thanks for the pull request! It seems as though this PR is breaking one of the Travis tests. Please look into fixing it and I'd be happy to merge it once the issue is resolved :)

**Comment by sugarshin** [comment]
I fixed test. Because this tests for only Firefox.

**Comment by Nickersoft** [comment]
Thanks!

**Comment by sugarshin** [comment]
Thanks. please bump version, also publish to npm.

**Comment by sugarshin** [comment]
@Nickersoft ping

**Comment by Nickersoft** [comment]
@sugarshin New version was just published (v0.0.13)!

**Comment by sugarshin** [comment]
Thanks!

**Pull request merged**
