### PR TITLE
Check if the icon is null

### LINKED ISSUE #178: Passing in null for an icon causes a runtime error
If you pass in null to Push.create's options, you get a runtime error because of this line:
https://github.com/Nickersoft/push.js/blob/master/src/agents/DesktopAgent.js#L30

Where it checks if icon is a string OR undefined, but doesn't handle the null case.

### PR DESCRIPTION
**Pull request by raybooysen**
Fixes #178

### CODE REVIEW

**Comment by raybooysen** [comment]
I don't quite get why this is failing on travis, node is throwing exceptions

**Comment by Nickersoft** [comment]
First of all, thanks for the PR! Sorry this initially passed under the radar.

Damn.. it's a fairly well-known [Node issue](https://github.com/nodejs/node/issues/20325) that is really recent. Has nothing to do with what you wrote. I think the build is failing on master. I'll look into getting a fix out today.

**Comment by raybooysen** [comment]
The build passes if you force the node version to 8.  I can do that as part of this PR?

**Comment by Nickersoft** [comment]
@raybooysen Ah yeah, I've recently discovered it's an issue with Node 10. You can force Travis to use the LTS version by [updating the correct YAML property](https://github.com/Nickersoft/push.js/blob/master/.travis.yml#L8). I'd recommend v8.11.3, as I think that's the current LTS.

**Comment by raybooysen** [comment]
Done, build green

**Comment by raybooysen** [comment]
Is it possible to have this merged and released?

**Comment by Nickersoft** [comment]
@raybooysen Sorry! I think I saw your message a few days ago and meant to release and completely forgot. I'll merge it in now and draft a release when I get home.

**Pull request merged**
